import type { Config } from 'tailwindcss';

/** Material-style palette from HappyBank design system (fonts unchanged — see app/fonts.ts). */
const config: Config = {
  darkMode: 'class',
  content: ['app/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      colors: {
        error: '#b41340',
        'error-dim': '#a70138',
        'on-tertiary-container': '#621837',
        'tertiary-fixed-dim': '#ee8aac',
        outline: '#777774',
        surface: '#f8f6f2',
        'on-tertiary-fixed-variant': '#6d2140',
        'on-secondary-fixed': '#463600',
        secondary: '#705900',
        primary: '#3e52b9',
        'surface-variant': '#deddd8',
        'surface-dim': '#d5d4d0',
        'on-surface': '#2e2f2d',
        'on-error-container': '#510017',
        'on-background': '#2e2f2d',
        'secondary-fixed': '#fdd34d',
        'inverse-primary': '#8093fe',
        'primary-fixed-dim': '#788bf6',
        background: '#f8f6f2',
        'on-secondary-fixed-variant': '#675200',
        'on-primary-fixed': '#000000',
        tertiary: '#923f5f',
        'tertiary-fixed': '#fe97b9',
        'primary-container': '#8899ff',
        'on-primary-fixed-variant': '#001c84',
        'tertiary-dim': '#843353',
        'error-container': '#f74b6d',
        'on-secondary': '#fff2d4',
        'secondary-container': '#fdd34d',
        'outline-variant': '#aeadaa',
        'on-primary-container': '#00156d',
        'surface-bright': '#f8f6f2',
        'secondary-fixed-dim': '#eec540',
        'primary-dim': '#3145ac',
        'on-surface-variant': '#5b5c59',
        'on-error': '#ffefef',
        'surface-container-lowest': '#ffffff',
        'surface-tint': '#3e52b9',
        'primary-fixed': '#8899ff',
        'inverse-on-surface': '#9e9d99',
        'tertiary-container': '#fe97b9',
        'inverse-surface': '#0e0e0d',
        'surface-container-low': '#f2f1ec',
        'secondary-dim': '#624d00',
        'on-tertiary-fixed': '#420020',
        'surface-container-highest': '#deddd8',
        'surface-container': '#e9e8e4',
        'on-primary': '#f2f1ff',
        'on-secondary-container': '#5c4900',
        'surface-container-high': '#e4e2de',
        'on-tertiary': '#ffeff1',
      },
    },
  },
};

export default config;
